version: '3.9'

services:
  internal:
    image: dockerrepo.softdesign.dk:5000/sample-${BRANCH_NAME}:latest
    command:  ["uvicorn", "sample.server:app", "--proxy-headers", "--host", "0.0.0.0", "--port", "8000", "--workers", "2", "--log-level", "error"]

    networks:
      - synchronicer
      - redis-nw

    # volumes:
    #   - sample_data:/app/apps/sample/data

    ports:
      - 6231:8000

    environment:
      - PYTHON_ENV=${PYTHON_ENV}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_JSON=true

    # logging:
    #   driver: syslog
    #   options:
    #     syslog-address: 'udp://logstash2:514'
    #     syslog-format: 'rfc3164'
    #     tag: 'sample_internal'

    healthcheck:
      test: 'curl --fail http://localhost:8000/sample/health || exit 1'
      interval: 60s
      retries: 5
      start_period: 5s
      timeout: 5s

    deploy:
      replicas: 2
      mode: replicated

      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

      update_config:
        parallelism: 1
        delay: 0s
        failure_action: pause
        monitor: 0s
        order: start-first
        max_failure_ratio: 0

  external:
    image: dockerrepo.softdesign.dk:5000/sample-${BRANCH_NAME}:latest
    command:  ["uvicorn", "sample.external_server:app", "--proxy-headers", "--host", "0.0.0.0", "--port", "8000", "--workers", "2", "--log-level", "error"]

    networks:
      - synchronicer
      - redis-nw

    # volumes:
    #   - sample_data:/app/apps/sample/data

    ports:
      - 6232:8000

    environment:
      - PYTHON_ENV=${PYTHON_ENV}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_JSON=true

    # logging:
    #   driver: syslog
    #   options:
    #     syslog-address: 'udp://logstash2:514'
    #     syslog-format: 'rfc3164'
    #     tag: 'sample_external'

    healthcheck:
      test: 'curl --fail http://localhost:8000/sample/health || exit 1'
      interval: 60s
      retries: 5
      start_period: 5s
      timeout: 5s

    deploy:
      replicas: 2
      mode: replicated

      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

      update_config:
        parallelism: 1
        delay: 0s
        failure_action: pause
        monitor: 0s
        order: start-first
        max_failure_ratio: 0


# volumes:
#   sample_data:
#     driver_opts:
#       type: 'nfs'
#       device: ':/volume1/${PYTHON_ENV}/sample'
#       o: 'addr=192.168.206.249,nfsvers=4'

networks:
  synchronicer:
    name: synchronicer
    external: true

  redis-nw:
    name: redis-nw
    external: true
