[mypy]
; Specify the Python version being used
python_version = 3.12

; Disallow untyped function definitions
; disallow_untyped_defs = True

; Disallow untyped calls
; disallow_untyped_calls = True

; Disallow untyped decorator functions
; disallow_untyped_decorators = True

; Disallow usage of Any types
; disallow_any_unimported = True
; disallow_any_expr = True
; disallow_any_decorated = True
; disallow_any_explicit = True
; disallow_any_generics = True

disable_error_code = import-untyped
ignore_missing_imports = True

; Enable strict optional checking
strict_optional = True

; Warn about unused ignores
warn_unused_ignores = True

; Warn about unreachable code
warn_unreachable = True

; Show error codes in messages
show_error_codes = True

; Enable incremental mode
incremental = True

; Being a monorepo we will suppres the duplicate module name error
explicit_package_bases = True

; Cache directory for mypy
cache_dir = ./.cache/.mypy

; Exclude files and directories
exclude = (?x)(
    ^build/
    | ^dist/
    | ^venv/
    | ^migrations/
    )

; Enable plugins if needed
; plugins = mypy_django_plugin.main
